@Aetna.MER.MCAuthAPI_HostAddress = https://localhost:7132
@McAuthApiSecret = your-secret-value-here

# HEADER SECRET TESTING - HOW-TO-USE:make sure Security:RequireSecretHeader is true in appsettings.json to test this. 'EnableClientCertificate' would have to be false, since they don't work with these http file tests.

POST {{Aetna.MER.MCAuthAPI_HostAddress}}/Authentication/authenticate
Content-Type: application/json
X-Api-Secret: {{McAuthApiSecret}}

{
  "authenticateUserRequest": {
    "userId": "chris.lintvedt",
    "currentPassword": "TestPassword123!",
    "userType": "Plansponsor",
    "domain": {
      "domainName": "example.com",
      "domainId": "1234"
    },
    "userAttributes": [
      {
        "key": "appname",
        "value": "Mobile"
      }
    ]
  }
}


###

GET {{Aetna.MER.MCAuthAPI_HostAddress}}/UserInfo/details/cust.meritain.com/chris.lintvedt
X-Api-Secret: {{McAuthApiSecret}}


###

POST {{Aetna.MER.MCAuthAPI_HostAddress}}/UserCommPref/details
Content-Type: application/json
X-Api-Secret: {{McAuthApiSecret}}

{
  "constituentType": "N/A",
  "ssk": [
    {
      "key": "userID/windowsaccountname",
      "value": "Test_123"
    },
    {
      "key": "Object_GUID",
      "value": "Unique value to test account"
    },
    {
      "key": "upn",
      "value": "user principal name"
    }
  ]
}

###

